package com.jsp.servlet;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.persistence.EntityManagerFactory;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;import com.jsp.controller.StudentController;
import com.jsp.model.Student;

@WebServlet(value = "/login")
public class LoginServlet extends HttpServlet {
	
	  
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		Database database = new Database();
		Student student = new Student();
		StudentController controller = new StudentController();
		
		String username = req.getParameter("username");
		String password = req.getParameter("password");
		
		PrintWriter printWriter = resp.getWriter();
		
		boolean loginresult = false;
		
		Student find = controller.find(username);
		
		if (find!=null) {
			if (find.getUsername().equals("admin123") && find.getPassword().equals("789456")) {

				printWriter.print("<!DOCTYPE html>\r\n"
						+ "<html>\r\n"
						+ "\r\n"
						+ "<head>\r\n"
						+ "  <title>User Dashboard</title>\r\n"
						+ "  <style>\r\n"
						+ "    body {\r\n"
						+ "      margin: 0;\r\n"
						+ "      padding: 0;\r\n"
						+ "      font-family: sans-serif;\r\n"
						+ "      background: linear-gradient(#141e30, #243b55);\r\n"
						+ "      display: flex;\r\n"
						+ "      align-items: center;\r\n"
						+ "      height: 100vh;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .dashboard-container {\r\n"
						+ "      display: flex;\r\n"
						+ "      \r\n"
						+ "      align-items: center;\r\n"
						+ "      width: 80%;\r\n"
						+ "      margin: auto;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .dashboard-box {\r\n"
						+ "    position: fixed;\r\n"
						+ "      top: 20;\r\n"
						+ "      left: 40;\r\n"
						+ "      width: 45%; /* Adjusted width */\r\n"
						+ "      padding: 40px;\r\n"
						+ "      background: rgba(0, 0, 0, .5);\r\n"
						+ "      box-sizing: border-box;\r\n"
						+ "      box-shadow: 0 15px 25px rgba(0, 0, 0, .6);\r\n"
						+ "      border-radius: 10px;\r\n"
						+ "      color: #fff;\r\n"
						+ "      text-align: center;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .dashboard-box h2 {\r\n"
						+ "      margin: 0 0 30px;\r\n"
						+ "      padding: 0;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .info {\r\n"
						+ "      margin-right: 10px;\r\n"
						+ "    }\r\n"
						+ "    \r\n"
						+ "    .info p{\r\n"
						+ "    	font-size:18px;\r\n"
						+ "        padding: 10px 0px;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .showpass {\r\n"
						+ "      display: flex;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .password {\r\n"
						+ "      display: none;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .show-password:checked + .data {\r\n"
						+ "      display: inline;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .menu {\r\n"
						+ "      position: fixed;\r\n"
						+ "      top: 20;\r\n"
						+ "      right: 0;\r\n"
						+ "      padding: 80px 40px;\r\n"
						+ "      background: rgba(0, 0, 0, .5);\r\n"
						+ "      box-sizing: border-box;\r\n"
						+ "      box-shadow: 0 15px 25px rgba(0, 0, 0, .6);\r\n"
						+ "      border-radius: 0 0 0 10px;\r\n"
						+ "      color: #fff;\r\n"
						+ "      text-align: right;\r\n"
						+ "    }\r\n"
						+ "    \r\n"
						+ "    .menu h2{\r\n"
						+ "    text-align: center;\r\n"
						+ "    margin-bottom: 30px;\r\n"
						+ "    }\r\n"
						+ "    .menu a {\r\n"
						+ "      display: block;\r\n"
						+ "      margin-top: 30px;\r\n"
						+ "      color: #03e9f4;\r\n"
						+ "      font-size: 16px;\r\n"
						+ "      text-decoration: none;\r\n"
						+ "      text-transform: uppercase;\r\n"
						+ "      transition: .5s;\r\n"
						+ "      letter-spacing: 4px;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .menu a:hover {\r\n"
						+ "      color: #fff;\r\n"
						+ "    }\r\n"
						+ "  </style>\r\n"
						+ "</head>\r\n"
						+ "\r\n"
						+ "<body>\r\n"
						+ "\r\n"
						+ "  <div class=\"dashboard-container\">\r\n"
						+ "    <!-- Dashboard Box -->\r\n"
						+ "    <div class=\"dashboard-box\">\r\n"
						+ "    <h2>Admin Dashboard</h2>\r\n"
						+ "\r\n"
						+ "    <!-- User Information (Replace with your dynamic data) -->\r\n"
						+ "    <div class=\"info\">\r\n"
						+ "      <p>Name : "+find.getName()+"</p>\r\n"
						+ "      \r\n"
						+ "    </div>\r\n"
						+ "\r\n"
						+ "    <div class=\"info\">\r\n"
						+ "      <p>Email : "+find.getEmail()+"</p>\r\n"
						+ "      \r\n"
						+ "    </div>\r\n"
						+ "\r\n"
						+ "    <div class=\"info\">\r\n"
						+ "      <p>Username : "+find.getUsername()+"</p>\r\n"
						+ "      \r\n"
						+ "    </div>\r\n"
						+ "\r\n"
						+ "    <div class=\"info\">\r\n"
						+ "      <label for=\"password\">Password:</label>\r\n"
						+ "      <input type=\"checkbox\" class=\"show-password\">\r\n"
						+ "      <p class=\"data password\">"+find.getPassword()+"</p>\r\n"
						+ "    </div>\r\n"
						+ "  </div>\r\n"
						+ "\r\n"
						+ "    <!-- Menu -->\r\n"
						+ "    <div class=\"menu\">\r\n"
						+ "    <h2>Menu</h2>\r\n"
						+ "    <hr>\r\n"
						+ "      <a href=\"registerform.html\">Register Student</a>\r\n"
						+ "      <a href=\"view.html\">View Details</a>\r\n"
						+ "      <a href=\"updateform.html\">Update Details</a>\r\n"
						+ "      <a href=\"deleteform.html\">Delete Details</a>\r\n"
						+ "    </div>\r\n"
						+ "  </div>\r\n"
						+ "\r\n"
						+ "</body>\r\n"
						+ "\r\n"
						+ "</html>\r\n"
						+ "");
				
			} else {
				printWriter.print("<!DOCTYPE html>\r\n"
						+ "<html>\r\n"
						+ "<head>\r\n"
						+ "  <title>User Dashboard</title>\r\n"
						+ "  <style>\r\n"
						+ "    body {\r\n"
						+ "      margin: 0;\r\n"
						+ "      padding: 0;\r\n"
						+ "      font-family: sans-serif;\r\n"
						+ "      background: linear-gradient(#141e30, #243b55);\r\n"
						+ "      display: flex;\r\n"
						+ "      justify-content: center;\r\n"
						+ "      align-items: center;\r\n"
						+ "      height: 100vh;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .dashboard-box {\r\n"
						+ "      width: 400px;\r\n"
						+ "      padding: 40px;\r\n"
						+ "      background: rgba(0,0,0,.5);\r\n"
						+ "      box-sizing: border-box;\r\n"
						+ "      box-shadow: 0 15px 25px rgba(0,0,0,.6);\r\n"
						+ "      border-radius: 10px;\r\n"
						+ "      color: #fff;\r\n"
						+ "      text-align: center;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .dashboard-box h2 {\r\n"
						+ "      margin: 0 0 30px;\r\n"
						+ "      padding: 0;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .info {\r\n"
						+ "      display: flex;\r\n"
						+ "      text-align: center;\r\n"
						+ "      justify-content: space-between;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .data {\r\n"
						+ "      margin-right: 10px;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .showpass {\r\n"
						+ "      display: flex;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .password {\r\n"
						+ "      display: none;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "    .show-password:checked + .data {\r\n"
						+ "      display: inline;\r\n"
						+ "    }\r\n"
						+ "\r\n"
						+ "		.dashboard-box a{\r\n"
						+ "        	display: block;\r\n"
						+ "            color: #03e9f4;\r\n"
						+ "            font-size: 13px;\r\n"
						+ "            text-decoration: none;\r\n"
						+ "            text-transform: uppercase;\r\n"
						+ "            transition: .5s;\r\n"
						+ "            text-align: left;\r\n"
						+ "            letter-spacing: 1px;\r\n"
						+ "            \r\n"
						+ "        }\r\n"
						+ "        .dashboard-box a:hover {    \r\n"
						+ "            color: #fff;    \r\n"
						+ "        }"
						
						+ "  </style>\r\n"
						+ "</head>\r\n"
						+ "<body>\r\n"
						+ "\r\n"
						+ "<div class=\"dashboard-box\">\r\n"
						+ "  <h2>Student Dashboard</h2>\r\n"
						+ "\r\n"
						+ "  <div class=\"info\">\r\n"
						+ "    <p>Name :</p>\r\n"
						+ "    <p class=\"data\">"+find.getName()+"</p>\r\n"
						+ "  </div>\r\n"
						+ "\r\n"
						+ "  <div class=\"info\">\r\n"
						+ "    <p>Email :</p>\r\n"
						+ "    <p class=\"data\">"+find.getEmail()+"</p>\r\n"
						+ "  </div>\r\n"
						+ "\r\n"
						+ "  <div class=\"info\">\r\n"
						+ "    <p>Username :</p>\r\n"
						+ "    <p class=\"data\">"+find.getUsername()+"</p>\r\n"
						+ "  </div>\r\n"
						+ "<div class=\"info\">\r\n"
						+ "    <p>Contact :</p>\r\n"
						+ "    <p class=\"data\">"+find.getContact()+"</p>\r\n"
						+ "  </div>\r\n"
						+ "  <div class=\"info\">\r\n"
						+ "    <label for=\"password\">Password:</label>\r\n"
						+ "    <input type=\"checkbox\" class=\"show-password\">\r\n"
						+ "    <p class=\"data password\">"+find.getPassword()+"</p>\r\n"
						+ "  </div>\r\n"
						+ "<a href=\"forgetpassword.html\" class=\"forgetpassword\">Forget Password?</a>"
						+ "</div>\r\n"
						+ "\r\n"
						+ "</body>\r\n"
						+ "</html>\r\n");
			} 
		} else {
			printWriter.print("<!DOCTYPE html>\r\n"
					+ "<html>\r\n"
					+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
					+ "<style>\r\n"
					+ "\r\n"
					+ "h1{\r\n"
					+ "color: white;\r\n"
					+ "}\r\n"
					+ "</style>\r\n"
					+ "<body>\r\n"
					+ "<center> <h1> Login Failed. Invalid Credentials try again</h1></center>\r\n"
					+ "</body>\r\n"
					+ "</html>\r\n");
			
			RequestDispatcher requestDispatcher = req.getRequestDispatcher("loginform.html");
			requestDispatcher.include(req, resp);
		}
	}
}